AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CreateThumbnail:
    Properties:
      CodeUri: s3://etude-for-lambda/8656b7922bd76ed228d5c594a86b884e
      Events:
        CreateThumbnailEvent:
          Properties:
            Bucket:
              Ref: SrcBucket
            Events: s3:ObjectCreated:*
          Type: S3
      Handler: createthumbnail.handler
      Policies: AWSLambdaExecute
      Runtime: nodejs6.10
      Timeout: 60
    Type: AWS::Serverless::Function
  SrcBucket:
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
